username = "@demolemon:matrix.org"
password = "matrixLYM20050411."

### Please fill in your username and password above.
###
### Robrix does not yet have a login splash screen.
### Thus, on desktop platforms, we allow the user to
### pass in a username and password as command line arguments.
###
### However, on mobile platforms, there is no way to reliably
### pass in command line arguments.
### Instead, we enable the mobile apps to read them from a copy
### of this file that is included in the app package files.
###
### Only the two username and password fields are supported.
###
### Note that for obvious reasons you should not commit this file
### or upload it to a public repo with your actual username and password in it.
### Thus, we have added it to the .gitignore file.
